url: https://www.excelsis.uk
show_drafts: false
exclude:
  - netlify.toml
  - README.md
markdown: kramdown
"[markdown]": {
        "editor.quickSuggestions": true
    }
kramdown:
math_engine: KaTex
gems:
  - jekyll-liquify
